packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@embedded-postgres/linux-x64"
  - "@embedded-postgres/linux-arm64"
  - "@embedded-postgres/darwin-x64"
  - "@embedded-postgres/darwin-arm64"
  - "@embedded-postgres/windows-x64"
  - "@prisma/engines"
  - "prisma"
  - "@nestjs/core"
